### ISSUE TITLE
Initial Repo Setup

### ISSUE THREAD

**Issue by Nick3530078** [jhartm26/Epsilon#10]
Get the repository smoothed out, and make sure everyone is up to date.

**Comment by jhartm26** [comment]
Alright, this is a note for when you guys are wanting to pull or commit the code. As of right now I haven't figured out how were each going to keep of code on each of our computers up to date without cloning the repository each time, however I have figured out committing to a basic degree. So as a basis when you want to commit changes do these things: 1. Make a branch to the main line. (This is done by pulling up the drop down on branches and typing the name you want to set for the branch) 2. Add your files to this branch, NOT THE MAIN ONE, it will automatically replace the ones cloned into that branch. and 3. Make a pull request to compare the two branches and make the changes to the main branch. I haven't tested this last step yet, but this is basically the form we will use. The one thing we want to note is that after we are finished with a branch or that branch's issue we will want to close it once it fixed/implemented.

**Comment by jhartm26** [comment]
At this time I believe the repository is fully setup for use though it will be changed as we move on and improve, so I will be closing this issue.
