### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by Nick3530078** [jhartm26/Epsilon#12]
Get the basic infrastructure for working together.

**Comment by jhartm26** [comment]
The process for updating the project with new code is documented in the Repo setup issue. Any other questions on github and its usage should be sent through discord towards Jacob(me). I will continue researching this websites usage so as to be capable of answering your questions. At this point you all should be able to access both this repository and the active project through a localhost server. at this point I will look into updating our personal code easier with the online repo code.

**Comment by jhartm26** [comment]
Right so I need one of you guys to test this to see if this works for people who arent the owner of the repo. By downloading github desktop the branching and committing of code is much simpler and in one place. For those of you willing to try it out you can however if it doesn't work for everyone then we will have to use the process of copying the code every time we need to make a change. This will conclude this issue when everyone has read the included information
