### ISSUE TITLE
Create Additional Color Theme Sets

### ISSUE THREAD

**Issue by jhartm26** [jhartm26/Epsilon#40]
Multiple color schemes being available will encourage individuality and interaction with the website

**Comment by Chickad33** [comment]
I love using coolors. It would be nice to see some more vibrant color themes or even a dark theme. Especially if we plan on marketing this to a variety of age groups. I will try to add some different palettes here soon.

**Comment by kiptaylor** [comment]
my fav is the 7th and the 6th and finally the last

**Comment by jhartm26** [comment]
Color Preferences: 7 6 1 9 8 2 3 5 4
This in order of the palettes in the document.

**Comment by yonitaweiszhauz** [comment]
Color Preference: 9, 2, 7, 6, 8, 3, 1, 5, 4

**Comment by Nick3530078** [comment]
From best to worst: 9, 2, 7, 6, 3, 1, 8, 5, 4

**Comment by jjgrayg** [comment]
Best to worst: 9, 1, 7, 2, 3, 5, 6, 4, 8

**Comment by mseller8** [comment]
best to worse: 9,2,7,6,3,8,1,5,4

**Comment by jhartm26** [comment]
I am going to close these votes and as Jarod placed four options within the theme drop down we will go with the four most voted for. These are the 2nd, 6th, 7th, and 9th in the word doc..
[Color.Palettes (2).docx](https://github.com/jhartm26/Epsilon/files/7583225/Color.Palettes.2.docx)
