### ISSUE TITLE
Tab Name

### ISSUE THREAD

**Issue by Nick3530078** [jhartm26/Epsilon#80]
Change the tab name from SWIFT Taskbook to Get Stuff Done.

**Comment by tobirix** [comment]
Hello @Nick3530078
do you mean the title in [header.tpl](https://github.com/jhartm26/Epsilon/blob/main/views/header.tpl) ?
If yes, I would like to do it :)

**Comment by Nick3530078** [comment]
Pull request made on 11/30/2021

**Comment by Nick3530078** [comment]
merged on 12/1
