### ISSUE TITLE
Solidify dates

### ISSUE THREAD

**Issue by jhartm26** [jhartm26/Epsilon#9]
Add dates next to Today/Tomorrow (or yesterday/day after tomorrow if we add more days)

**Comment by Nick3530078** [comment]
Yesterday - Class/Initial Setup
Today - N/A
Impedances - Plenty of time, other work, etc.

**Comment by Nick3530078** [comment]
Yesterday - N/A
Today - "Added" default_app code provided by the professor to swift.py
Impedances - Plenty of time left, etc.

**Comment by Nick3530078** [comment]
Yesterday - "Added" default_app code provided by the professor to swift.py
Today - N/A
Impedances - Plenty of time left, etc.

**Comment by Nick3530078** [comment]
Yesterday - N/A
Today - N/A
Impedances - N/A

Will start work tomorrow or Sunday.

**Comment by Nick3530078** [comment]
Y-N/A
Today-Everything (Dates (month followed by day)) added below the tomorrow and today headers.
Impedances - Not knowing anything about the environment. W3 schools carried me.
